### ISSUE TITLE
Setup: Locate default Simulator/Derived data directories

### ISSUE THREAD

**Issue by ChristianKienle** [ChristianKienle/Core-Data-Editor#17]
Now that Core Data Editor no longer is sandboxed it can locate the default sim/derived data directories and use those to make the initial setup easier/semi-automatic.

**Comment by robinmacharg** [comment]
For reference, a fuller discussion of @yepher's solution can be found on [his github site](https://github.com/yepher/CoreDataUtility), including a Swift version of the above code.

**Comment by ChristianKienle** [comment]
thanks. I will look into it.

**Comment by steprescott** [comment]
Any update on a fix for this as this App is a great tool when debugging Core Data issues. I liked it so much that I bought it on the App Store in support.

**Comment by ChristianKienle** [comment]
@yepher @steprescott fixed

https://github.com/ChristianKienle/Core-Data-Editor/pull/41

Closing this issue.
