### ISSUE TITLE
Improvement: Schema Refresh

### ISSUE THREAD

**Issue by codepushr** [ChristianKienle/Core-Data-Editor#26]
I would love to hit CMD+R to refresh the schema because right now if the data changes in the background the labels don't.
Having the application inserting a new row does update the entry in Core-Data-Editor if you click on the Model/Table but the little label indicating the row count never gets updated!

Anyway really well and useful application! Keep it up.

**Comment by gerardp** [comment]
+ 1

**Comment by ChristianKienle** [comment]
@gerardp Working on it. :)

**Comment by fonkadelic** [comment]
+ 1

**Comment by mnort9** [comment]
+1

**Comment by ChristianKienle** [comment]
@codepushr @gerardp @fonkadelic @mnort9 I have finally implemented it... Sorry that it took so long. 

https://github.com/ChristianKienle/Core-Data-Editor/pull/40

I have resumed the development of Core Data Editor (starting a few weeks ago already). You should find the feature in develop and then in master shortly.
