### ISSUE TITLE
Exception on fresh launch of the app (running from LLDB)

### ISSUE THREAD

**Issue by altimac** [ChristianKienle/Core-Data-Editor#45]
[General] *** -[NSURL initFileURLWithPath:]: nil string parameter
2017-01-05 13:46:26.396153 Core Data Editor[36016:9285680] [General] (
	0   CoreFoundation                      0x00007fffb9933e7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffce51ecad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffb99b299d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fffbb2cf24a -[NSURL(NSURL) initFileURLWithPath:] + 131
	4   Foundation                          0x00007fffbb2cf1b1 +[NSURL(NSURL) fileURLWithPath:] + 45
	5   Core Data Editor                    0x00000001000143d9 -[CDEConfiguration modelURL] + 89
	6   Core Data Editor                    0x0000000100002914 -[CDEDocument modelURL] + 68
	7   Core Data Editor                    0x000000010000455b -[CDEDocument windowControllerDidLoadNib:] + 843
	8   AppKit                              0x00007fffb744bdc0 -[NSWindowController _windowDidLoad] + 826
	9   AppKit                              0x00007fffb73ebd93 -[NSWindowController window] + 110
	10  AppKit                              0x00007fffb7e24f4d -[NSDocument(NSPersistentUISupport) restoreDocumentWindowWithIdentifier:state:completionHandler:] + 161
	11  AppKit                              0x00007fffb7928dfd -[NSDocumentControllerPersistentRestoration loadedDocument:forAutoID:] + 165
	12  AppKit                              0x00007fffb792db59 __89-[NSDocumentController reopenDocumentForURL:withContentsOfURL:display:completionHandler:]_block_invoke_2 + 203
	13  CoreFoundation                      0x00007fffb98c97dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	14  CoreFoundation                      0x00007fffb98aa7e4 __CFRunLoopDoBlocks + 356
	15  CoreFoundation                      0x00007fffb98aa326 __CFRunLoopRun + 1878
	16  CoreFoundation                      0x00007fffb98a9974 CFRunLoopRunSpecific + 420
	17  HIToolbox                           0x00007fffb8e35acc RunCurrentEventLoopInMode + 240
	18  HIToolbox                           0x00007fffb8e35809 ReceiveNextEventCommon + 184
	19  HIToolbox                           0x00007fffb8e35736 _BlockUntilNextEventMatchingListInModeWithFilter + 71
	20  AppKit                              0x00007fffb73dbae4 _DPSNextEvent + 1120
	21  AppKit                              0x00007fffb7b5621f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
	22  AppKit                              0x00007fffb73d0465 -[NSApplication run] + 926
	23  AppKit                              0x00007fffb739ad80 NSApplicationMain + 1237
	24  Core Data Editor                    0x0000000100001de2 main + 34
	25  libdyld.dylib                       0x00007fffcee02255 start + 1
)

**Comment by ChristianKienle** [comment]
I cannot reproduce that. Can you reproduce it with the develop branch?
