### ISSUE TITLE
BitDefender complains CoreDataError is making modifications to the backups?

### ISSUE THREAD

**Issue by dchersey** [ChristianKienle/Core-Data-Editor#46]
I just started running BitDefender antivirus for Mac (2016) and I am getting notifications that Core Data Editor is trying to make modifications to my Time machine backups (I have enabled BitDefender's Time machine protection feature).  

Does this make any sense?  You can reproduce this with a trial version of Bitdefender ... it occurs when I open/close the app the first time.

**Comment by ChristianKienle** [comment]
Core Data Editor is not doing anything malicious. It was even sandboxed at some point in the past.

**Comment by ChristianKienle** [comment]
Can you attach a screenshot of the bit defender alert?

**Comment by dchersey** [comment]
Since I posted this, I have seen the same warning from other apps,
including some Apple apps.  So I am now considering this to be a BD issue
... and disregarding for now.

Thanks for responding; I think we can close this issue at this point.

David
